### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by r4ai** [r4ai/tinnitus-reducer-acrn#3]
- [x] Customization
  - [x] BPM (high priority) #10 
  - [x] Choosing right/left/both channels #10 
  - [x] Synth preset (low priority) #14 
  - [x] Fix tab index of config panel #53
- [ ] Features
  - [ ] Timer (decrease the BPM)
  - [x] Timer (stop the Sequence) #26
- [x] Setting
  - [x] Load/Save settings
    - [x] frequency (high priority) #4 
    - [x] volume (high priority)    #4
    - [x] bpm (high priority)       #4
    - [x] synth preset (low priority) #14 
  - [x] Export/Import settings #15 
- [ ] Others
  - [x] Publish as webapp (using GitHub Pages) #11 
  - [ ] Publish as mobile app (using Tauri 2.0 Alpha) (low priority)
  - [x] Publish as desktop app
  - [x] Support PWA #31 
  - [ ] Add loading screen (low priority)
  - [x] Add favicon #13 
  - [x] Add custom title bar #9 
  - [ ] Add updater
  - [ ] publish on microsoft store (windows) (low priority)
